#!/bin/sh

source "$HOME/.config/displays/setup.conf"
MODE_FILE="$HOME/.config/displays/mode"
MODE="$(cat "$MODE_FILE")"

function set_mode {
  echo "$1" > "$MODE_FILE"
}

case "$1" in
  "")
    exec "$0" "$MODE"
    ;;
  "single")
    xrandr|grep connected| grep -v "$INTERNAL"|cut -d ' ' -f1|xargs -I '{}' xrandr --output '{}' --off
    xrandr --output "$INTERNAL" --auto
    set_mode single
    ;;
  "other")
    xrandr --output "$INTERNAL" --off 
    xrandr --output "$EXTERNAL" --primary --auto --rotate normal
    fixdpi 1.3
    set_mode other
    ;;
  "dual")
    [ `xrandr|grep ' connected'|wc -l` -eq 2 ] || exit 1
    source "$HOME/.config/displays/setup.conf"
    xrandr --output "$EXTERNAL" --auto --rotate normal --primary \
           --output "$INTERNAL" --auto --rotate normal --right-of "$EXTERNAL"
    # xrandr --output "$EXTERNAL" --auto --rotate right --right-of "$INTERNAL"
    set_mode dual
    ;;
  "mirror")
    source "$HOME/.config/displays/setup.conf"
    xrandr --output "$EXTERNAL" --auto
    xrandr --output "$INTERNAL" --auto
    RESOLUTION=$(xrandr|awk "/$INTERNAL/{getline;print \$1}")
    echo $RESOLUTION
    xrandr --output "$EXTERNAL" --mode "$RESOLUTION" --same-as "$INTERNAL"
    set_mode mirror
    ;;
  "next-mode")
    case "$MODE" in
      "single") set_mode "other"  ;;
      "other" ) set_mode "dual"   ;;
      "dual"  ) set_mode "mirror" ;;
      "mirror") set_mode "single" ;;
    esac
    exec "$0"
    ;;
  "prev-mode")
    case "$MODE" in
      "other" ) set_mode "single" ;;
      "dual"  ) set_mode "other"  ;;
      "mirror") set_mode "dual"   ;;
      "single") set_mode "mirror" ;;
    esac
    exec "$0"
    ;;
esac
chwp
